# This is a basic workflow that is manually triggered

name: ALL-HW ARM CI

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      binary:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Binary for the task'
        # Default value if no value is explicitly provided
        default: '/test/HelloW.axf'
        # Input has to be provided for the workflow to run
        required: true
      file:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Input data for the task'
        # Default value if no value is explicitly provided
        default: '/test/input1.txt'
        # Input has to be provided for the workflow to run
        required: true
      api_key:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'API key for the all-hw.com service'
        # Default value if no value is explicitly provided
        default: 'ba1e491b-331b-4e35-b799-f714b8505843'
        # Input has to be provided for the workflow to run
        required: true
      timeout:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Task timeout'
        # Default value if no value is explicitly provided
        default: '60'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_task:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out repository
      uses: actions/checkout@main
    - name: Test env
      env: 
        INPUT_BINARY: ${{ github.event.inputs.binary }}
        INPUT_FILE: ${{ github.event.inputs.file }}
        INPUT_TIMEOUT: ${{ github.event.inputs.timeout }}
        INPUT_API_KEY: ${{ github.event.inputs.api_key }} 
      run: echo "binary - $INPUT_BINARY"
    - name: Start task
      env: 
        INPUT_BINARY: ${{ github.event.inputs.binary }}
        INPUT_FILE: ${{ github.event.inputs.file }}
        INPUT_TIMEOUT: ${{ github.event.inputs.timeout }}
        INPUT_API_KEY: ${{ github.event.inputs.api_key }} 
      run: curl -X POST -F firmware=./$INPUT_BINARY -F input=./$INPUT_FILE https://cloud.all-hw.com/ci/usertask?timeout=$INPUT_TIMEOUT&key=$INPUT_API_KEY
