# This is a basic workflow that is manually triggered

name: ALL-HW ARM CI

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      binary:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Binary for the task'
        # Default value if no value is explicitly provided
        default: '/test/HelloW.axf'
        # Input has to be provided for the workflow to run
        required: true
      input:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Input data for the task'
        # Default value if no value is explicitly provided
        default: '/test/input1.txt'
        # Input has to be provided for the workflow to run
        required: true
      api_key:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'API key for the all-hw.com service'
        # Default value if no value is explicitly provided
        default: 'ba1e491b-331b-4e35-b799-f714b8505843'
        # Input has to be provided for the workflow to run
        required: true
      timeout:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Task timeout'
        # Default value if no value is explicitly provided
        default: '60'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  run_task:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Start task
      run: echo `curl -X POST -F firmware=$GITHUB_ACTION_PATH$INPUT_BINARY -F input=$GITHUB_ACTION_PATH$INPUT_INPUT https://cloud.all-hw.com/ci?timeout=$INPUT_TIMEOUT&key=$INPUT_API_KEY`

